dependencies:
  - jdbc: true
  - jpa: true
  - mongodb: true
  - redis: true
  - gemfire: true
  - solr: true
  - elasticsearch: true
  - websocket: true
  - ws: true
  - jersey: true
  - rest: true
  - mobile: true
  - security: true
  - aop: true
  - jta-atomikos: true
  - jta-bitronix: true
  - batch: true
  - integration: true
  - hornetq: true
  - amqp: true
  - mail: true
  - freemarker: true
  - velocity: true
  - groovy-templates: true
  - thymeleaf: true
  - social-facebook: true
  - social-linkedin: true
  - social-twitter: true
  - actuator: true
  - cloud-connectors: true
  - remote-shell: true
